gatewaybridge:
  build: .
  command: make serve
  ports:
    - "1700/udp:1700/udp"
  volumes:
    - ./:/go/src/github.com/migiz/lora-gateway-bridge
  links:
    - mosquitto
  environment:
    - MQTT_SERVER=tcp://172.31.0.10:1883
    - TEST_MQTT_SERVER=tcp://172.31.0.10:1883

mosquitto:
  image: registry.ng.bluemix.net/etteplan/mosquitto
